ims/approvals/urls.py
# urls.py
from django.urls import path
from .views import create_approval_request, approval_list, approve_request, disapprove_request, access_denied, get_experiments

urlpatterns = [
  path('create/', create_approval_request, name='create_approval_request'),
  path('', approval_list, name='approval_list'),
  path('approve/<int:pk>/', approve_request, name='approve_request'),
  path('disapprove/<int:pk>/', disapprove_request, name='disapprove_request'),
  path('access-denied/', access_denied, name='access_denied'),
  path('get_experiments/<int:project_id>/', get_experiments, name='get_experiments'),
]

ims/ims/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ims.views import *
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', CustomLogin.as_view(),name='login'),
    path('accounts/logout/', views.logout_view,name='logout'),
    re_path(r'^', include('metadata.urls')),
    path('approvals/', include('approvals.urls')),  # Include the approvals app URLs
    path('lab/', include('lab.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ims/approvals/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User

from metadata.models import Experiment, Project

class ApprovalRequest(models.Model):
  STATUS_CHOICES = [
      ('pending', 'Pending'),
      ('approved', 'Approved'),
      ('disapproved', 'Disapproved'),
  ]
  title = models.CharField(max_length=255)
  document = models.FileField(upload_to='documents/')
  status = models.CharField(max_length=11, choices=STATUS_CHOICES, default='pending')
  created_by = models.ForeignKey(User, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)
  approved_by = models.ForeignKey(User, null=True, blank=True, related_name='approvals', on_delete=models.SET_NULL)
  approved_at = models.DateTimeField(null=True, blank=True)
  comments = models.CharField(max_length=500, null=True, blank=True)
  project = models.ForeignKey(Project, on_delete=models.RESTRICT, related_name='approval_requests')
  experiments = models.ManyToManyField(Experiment, related_name='approval_requests')

  def __str__(self):
    return f"Request by {self.created_by.username} - Status: {self.status}"

ims/approvals/forms.py
# forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import ApprovalRequest
from metadata.models import Project, Experiment
from metadata.utils import get_projects_for_user

class ApprovalRequestForm(forms.ModelForm):
  projects = forms.ModelChoiceField(queryset=Project.objects.none(), required=True)
  experiments = forms.ModelMultipleChoiceField(queryset=Experiment.objects.none(), required=True)
  class Meta:
    model = ApprovalRequest
    fields = ['projects', 'experiments', 'title', 'document']
    widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'document': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

  def __init__(self, *args, user=None, **kwargs):
    super(ApprovalRequestForm, self).__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.form_method = 'post'
    self.helper.add_input(Submit('submit', 'Submit'))
    if user is not None:
      self.fields['projects'].queryset = get_projects_for_user(user)  # Adjust according to your lab

    if 'projects' in self.data:
      try:
        project_id = int(self.data.get('projects'))
        self.fields['experiments'].queryset = Experiment.objects.filter(project_id=project_id)
      except (ValueError, TypeError):
        self.fields['experiments'].queryset = Experiment.objects.none()
    elif self.instance.pk:
      self.fields['experiments'].queryset = self.instance.project.experiment_set.all()

  def clean(self):
    cleaned_data = super().clean()
    project = cleaned_data.get('projects')
    experiments = cleaned_data.get('experiments')

    if project and (not experiments or experiments.count() == 0):
        raise forms.ValidationError("The selected project has no experiments. Please select a project with experiments.")

    return cleaned_data

ims/approvals/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.http import JsonResponse
from .forms import ApprovalRequestForm
from .models import ApprovalRequest
from user_profiles.models import UserProfile
from user_profiles.utils import is_admin_or_is_supervisor
from metadata.models import Experiment
from django.contrib.auth.decorators import login_required, user_passes_test

@login_required
def create_approval_request(request):
  if request.method == 'POST':
    form = ApprovalRequestForm(request.POST, request.FILES, user=request.user)
    if form.is_valid():
      approval_request = form.save(commit=False)
      approval_request.created_by = request.user
      # Set the project FK
      selected_project = form.cleaned_data.get('projects')
      approval_request.project = selected_project
      approval_request.save()

      # Set the many-to-many experiments
      selected_experiments = form.cleaned_data.get('experiments')
      approval_request.experiments.set(selected_experiments)

      return redirect('approval_list')
  else:
    form = ApprovalRequestForm(user=request.user)
  return render(request, 'create_request.html', {'form': form})

@login_required
def approval_list(request):
  # Assuming the user is logged in
  user = request.user

  # Attempt to get the UserProfile
  try:
    user_profile = UserProfile.objects.get(user=user)
  except UserProfile.DoesNotExist:
    # If the user does not have a profile, show a message
    return render(request, 'approval_list.html', {'approvals': [], 'is_supervisor': False, 'profile_exists': False, 'is_sequence_core': False})

  # Check if the user is a supervisor
  supervisor_status = is_admin_or_is_supervisor(user)

  # Check if the user is the sequence core user
  is_sequence_core = user.groups.filter(name='sequence_core').exists()

  # Get the lab associated with the user's profile
  lab = user_profile.lab

  if request.user == lab.supervisor:
    # If the user is a supervisor, show all requests for their lab
    approvals = ApprovalRequest.objects.filter(created_by__userprofile__lab=lab).select_related('project').prefetch_related('experiments').order_by('status')
  else:
    # If the user is not a supervisor, show only their own requests
    approvals = ApprovalRequest.objects.filter(created_by=user).select_related('project').prefetch_related('experiments').order_by('status')

  return render(request, 'approval_list.html', {'approvals': approvals, 'is_supervisor': supervisor_status, 'profile_exists': True, 'is_sequence_core': is_sequence_core})

@login_required
@user_passes_test(is_admin_or_is_supervisor) # Only allow supervisor to approve
def approve_request(request, pk):
  approval_request = get_object_or_404(ApprovalRequest, pk=pk)
  approval_request.status = 'approved'
  approval_request.approved_by = request.user  # Set the supervisor who approved
  approval_request.approved_at = timezone.now()  # Set the approval timestamp
  approval_request.save()
  return redirect('approval_list')


@login_required
@user_passes_test(is_admin_or_is_supervisor) # Only allow supervisor to approve
def disapprove_request(request, pk):
  approval_request = get_object_or_404(ApprovalRequest, pk=pk)
  if request.method == 'POST':
    # Handle the comment submission
    comment = request.POST.get('comment')
    approval_request.comments = comment
    approval_request.status = 'disapproved'
    approval_request.approved_by = request.user  # Set the supervisor who approved
    approval_request.approved_at = timezone.now()  # Set the approval timestamp
    approval_request.save()

  return redirect('approval_list')

def access_denied(request):
  return render(request, 'access_denied.html')

def get_experiments(request, project_id):
  experiments = Experiment.objects.filter(project_id=project_id)
  # Serialize the experiments into a list of dictionaries
  experiments_data = [{'id': experiment.id, 'name': experiment.name} for experiment in experiments]
  return JsonResponse({'experiments': experiments_data})

ims/approvals/templates/access_denied.html
<h1>Access Denied</h1>
<p>You do not have permission to access this site.</p>

ims/approvals/templates/approval_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
  @media (max-width: 767.98px) {

    /* XS and SM screens */
    table {
      border: 0;
    }

    thead {
      display: none;
      /* Hide header */
    }

    tbody tr {
      display: block;
      /* Display rows as block */
      margin-bottom: 1rem;
      border-bottom: 2px solid #ddd;
    }

    tbody tr td {
      display: flex;
      justify-content: space-between;
      padding-left: 50%;
      /* make space for label */
      position: relative;
      border: none;
      border-bottom: 1px solid #eee;
    }

    tbody tr td::before {
      content: attr(data-label);
      /* Pull label from data-label attr */
      width: 45%;
      /* Label width */
      padding-left: 15px;
      font-weight: bold;
      white-space: nowrap;
    }
  }
</style>
<script>
  $(document).ready(function () {
    $('#commentModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var approvalId = button.data('id'); // Extract info from data-* attributes
      var approvalTitle = button.data('title');

      // Update the modal's content
      var modal = $(this);
      modal.find('#approvalId').val(approvalId); // Set the approval ID in the hidden input
      modal.find('#commentForm').attr('action', '{% url "disapprove_request" 0 %}'.replace('0', approvalId)); // Set the form action
    });

    $('#submitButton').on('click', function () {
      $('#commentForm').submit(); // Programmatically submit the form
    });
  });
</script>
<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalLabel">Add Your Comment</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <form id="commentForm" method="POST" action="">
          {% csrf_token %}
          <div class="form-group">
            <label for="commentText">Comment</label>
            <textarea class="form-control" id="commentText" name="comment" rows="3" maxlength="500"></textarea>
          </div>
          <input type="hidden" id="approvalId" name="approval_id" value="">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submitButton">Submit</button>
      </div>
    </div>
  </div>
</div>
<h2 class="mt-3">Approval Requests</h2>
<br>
<div class="container">
  {% if not profile_exists %}
  <div class="alert alert-warning">
    You do not have a user profile. Please contact Admin to create one for so you can access approval requests.
  </div>
  {% else %}
  <a href="{% url 'create_approval_request' %}"><button type="button" class="btn btn-primary mb-4">Create New Approval
      Request</button></a>
  {% if approvals %}
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-pending-tab" data-bs-toggle="tab" data-bs-target="#nav-pending" type="button" role="tab" aria-controls="nav-pending" aria-selected="true">Pending Approval Requests</button>
      <button class="nav-link" id="nav-processed-tab" data-bs-toggle="tab" data-bs-target="#nav-processed" type="button" role="tab" aria-controls="nav-processed" aria-selected="false">Processed Approval Requests</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active p-4" id="nav-pending" role="tabpanel" aria-labelledby="nav-pending-tab">
      <table class="table table-bordered table-hover table-sm data_table pt-4" data-page-length='3'>
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Project</th>
            <th>Experiments</th>
            <th>Document</th>
            <th>Created At</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        {% for approval in approvals %}
        {% if approval.status == 'pending' %}
        <tr
          class="{% if approval.status == 'approved' %}table-success{% elif approval.status == 'disapproved' %} table-danger {% else %} {% endif %}">
          <td data-label="Title">{{ approval.title }}</td>
          <td data-label="User">{{ approval.created_by.get_full_name }}</td>
          <td data-label="Project"><a href="{% url 'detailProject' approval.project.pk %}">{{ approval.project.name }}</a></td>
          <td data-label="Experiments">
            {% for experiment in approval.experiments.all %}
              <a href="{% url 'detailExperiment' experiment.pk %}">{{ experiment.name }}</a>{% if not forloop.last %}, {% endif %}
            {% empty %}
              None
            {% endfor %}
          </td>
          <td data-label="Document"><a href="{{ approval.document.url }}" target="_blank">Download</a></td>
          <td data-label="Created At">{{ approval.created_at|date:"Y-m-d H:i" }}</td>
          <td data-label="Status">{{ approval.get_status_display }}</td>
          <td data-label="Actions">
            {% if is_supervisor %}
            {% if approval.status == 'pending' %}
            <div class="d-grid gap-2">
              <a href="{% url 'approve_request' approval.pk %}" class="btn btn-outline-success btn-sm">
                Approve
              </a>
              <button class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#commentModal"
                data-id="{{ approval.pk }}">Disapprove</button>
            </div>
            {% endif %}
            {% endif %}
          </td>
        </tr>
        {% endif%}
        {% endfor %}
      </table>
    </div>
    <div class="tab-pane fade p-4" id="nav-processed" role="tabpanel" aria-labelledby="nav-processed-tab">
      <table class="table table-bordered table-hover table-sm requests data_table pt-4" data-page-length='3'>
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Project</th>
            <th>Experiments</th>
            <th>Document</th>
            <th>Created At</th>
            <th>Status</th>
            <th>Approved/Disapproved By</th>
            <th>Approved/Disapproved At</th>
            <th>Comment</th>
          </tr>
        </thead>
        {% for approval in approvals %}
        {% if approval.status != 'pending' %}
        <tr
          class="{% if approval.status == 'approved' %}table-success{% elif approval.status == 'disapproved' %} table-danger {% else %} {% endif %}">
          <td data-label="Title">{{ approval.title }}</td>
          <td data-label="User">{{ approval.created_by.get_full_name }}</td>
          <td data-label="Project"><a href="{% url 'detailProject' approval.project.pk %}">{{ approval.project.name }}</a></td>
          <td data-label="Experiments">
            {% for experiment in approval.experiments.all %}
              <a href="{% url 'detailExperiment' experiment.pk %}">{{ experiment.name }}</a>{% if not forloop.last %}, {% endif %}
            {% empty %}
              None
            {% endfor %}
          </td>
          <td data-label="Document"><a href="{{ approval.document.url }}" target="_blank">Download</a></td>
          <td data-label="Created At">{{ approval.created_at|date:"Y-m-d H:i" }}</td>
          <td data-label="Status">{{ approval.get_status_display }}</td>
          <td data-label="Processed By">
            {% if approval.approved_by %}
            {{ approval.approved_by.get_full_name }}
            {% else %}
            N/A
            {% endif %}
          </td>
          <td data-label="Processed At">
            {% if approval.approved_by %}
            {{ approval.approved_at|date:"Y-m-d H:i" }}
            {% else %}
            N/A
            {% endif %}
          </td>
          <td data-label="Comment">{{ approval.comments }}</td>
        </tr>
        {% endif%}
        {% endfor %}
      </table>
    </div>
    {% else %}
    <p>No approval requests available for your lab.</p>
    {% endif %}
    <br>
    {% endif %}
    </div>
  </div>





{% endblock %}

ims/approvals/templates/approval_request_created_email_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Approval Request</title>
  <style>
    body {
      background-color: #f4f4f4;
    }

    .container {
      margin-top: 20px;
      background: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .button {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #007BFF;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }

    .footer {
      margin-top: 20px;
      font-size: 12px;
      color: #999;
    }

    .footer img {
      max-width: 40rem;
      /* Adjust the size as needed */
      height: auto;
    }
  </style>
</head>

<body>
  <div class="container">
    <h1 class="text-primary">Approval Request</h1>
    <p>Dear {{ approver_name }},</p>
    <p>I am writing to request your approval for the following:</p>
    <p><strong>Request Details:</strong></p>
    <ul>
      <li><strong>Request Type:</strong> {{ request_type }}</li>
      <li><strong>Title:</strong> {{ request_title }}</li>
      <li><strong>Requested By:</strong> {{ requester_name }}</li>
    </ul>
    <p>Please review the request at your earliest convenience. You can approve or deny the request using the button
      below:</p>
    <a href="{{ approval_link }}" class="button">Review Request</a>
    <p>Thank you for your attention to this matter.</p>
    <p>Best regards,<br>{{ requester_name }}</p>
    <div class="footer">
      <p>This is an automated message. Please do not reply.</p>
      <img src="{{ logo_url }}" alt="Lupien Lab Logo">
    </div>
  </div>
</body>

</html>

ims/approvals/templates/approval_request_processed_email_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Approval Request</title>
  <style>
    body {
      background-color: #f4f4f4;
    }

    .container {
      margin-top: 20px;
      background: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .button {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #007BFF;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }

    .footer {
      margin-top: 20px;
      font-size: 12px;
      color: #999;
    }

    .footer img {
      max-width: 40rem;
      /* Adjust the size as needed */
      height: auto;
    }
  </style>
</head>

<body>
  <div class="container">
    <h1 class="text-primary">Request Processed</h1>
    <p>Dear {{ requester_name }},</p>
    <p>Your Request has been processed:</p>
    <p><strong>Request Details:</strong></p>
    <ul>
      <li><strong>Title:</strong> {{ request_title }}</li>
      <li><strong>Requested By:</strong> {{ requester_name }}</li>
      <li><strong>Processed By:</strong> {{ approver_name }}</li>
      <li><strong>Result:</strong> {{ result }}</li>
      <li><strong>comments:</strong> {{ comments }}</li>
    </ul>
    <p>Please review the request at your earliest convenience. You can view your requests using the button
      below:</p>
    <a href="{{ approval_link }}" class="button">View Request</a>
    <p>Thank you for your attention to this matter.</p>
    <p>Best regards,<br>{{ approver_name }}</p>
    <div class="footer">
      <p>This is an automated message. Please do not reply.</p>
      <img src="{{ logo_url }}" alt="Lupien Lab Logo">
    </div>
  </div>
</body>

</html>

ims/approvals/templates/create_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tags %}
{% load static %}




{% block content %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const projectSelect = document.getElementById('id_projects');
    const experimentSelect = document.getElementById('id_experiments');

    projectSelect.addEventListener('change', function () {
      const projectId = this.value;

      if (projectId) {  // Check if a project is selected
        fetch(`/approvals/get_experiments/${projectId}/`)
          .then(response => response.json())
          .then(data => {
            // Clear existing options
            experimentSelect.innerHTML = '';

            // Populate new options
            data.experiments.forEach(experiment => {
              const option = document.createElement('option');
              option.value = experiment.id;
              option.textContent = experiment.name;
              experimentSelect.appendChild(option);
            });
          })
          .catch(error => {
            console.error('There was a problem with the fetch operation:', error);
          });
      } else {
        // Clear experiments if no project is selected
        experimentSelect.innerHTML = '';
      }
    });
  });
</script>
<h2 class="mt-3">Create Approval Request</h2>
<br>
<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% crispy form %}
  </form>
</div>
{% endblock %}